# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import separatedvaluesfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ops', '0001_initial'),
        ('assets', '0002_auto_20180307_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('adhoc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ops.AdHoc')),
                ('playbook_path', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Playbook Path')),
                ('is_running', models.BooleanField(default=False, verbose_name='Is running')),
            ],
            bases=('ops.adhoc',),
        ),
        migrations.CreateModel(
            name='PlayBookTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ops.Task')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('password', models.CharField(blank=True, max_length=200, null=True, verbose_name='WebHook Password')),
                ('tags', separatedvaluesfield.models.TextSeparatedValuesField(blank=True, null=True, verbose_name='Tags')),
                ('ansible_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='devops.AnsibleRole', verbose_name='Ansible Role')),
                ('assets', models.ManyToManyField(blank=True, related_name='task', to='assets.Asset', verbose_name='Assets')),
                ('groups', models.ManyToManyField(blank=True, related_name='task', to='assets.Node', verbose_name='Asset Groups')),
                ('system_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='assets.SystemUser', verbose_name='System User')),
            ],
            bases=('ops.task',),
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('vars', jsonfield.fields.JSONField(blank=True, default={}, null=True, verbose_name='Vars')),
                ('assets', models.ManyToManyField(blank=True, related_name='variable', to='assets.Asset', verbose_name='Assets')),
                ('groups', models.ManyToManyField(blank=True, related_name='variable', to='assets.Node', verbose_name='Nodes')),
            ],
        ),
    ]
